// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalValentiniMariela.Conection;

namespace WebApiFinalValentiniMariela.Migrations
{
    [DbContext(typeof(DbHospitalContext))]
    [Migration("20221118185052_relaciones")]
    partial class relaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalValentiniMariela.Models.Hospital", b =>
                {
                    b.Property<int>("Hospital_Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Num_Camas")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Hospital_Cod");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("WebApiFinalValentiniMariela.Models.Medico", b =>
                {
                    b.Property<int>("Doctor_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Hopital_Cod")
                        .HasColumnType("int");

                    b.Property<int>("Hospital_Cod")
                        .HasColumnType("int");

                    b.HasKey("Doctor_No");

                    b.HasIndex("Hopital_Cod");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("WebApiFinalValentiniMariela.Models.Medico", b =>
                {
                    b.HasOne("WebApiFinalValentiniMariela.Models.Hospital", "Hospital")
                        .WithMany("Medicos")
                        .HasForeignKey("Hopital_Cod");
                });
#pragma warning restore 612, 618
        }
    }
}
